services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: passvault
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - passvault_pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - app-network
    ports:
      - "5432:5432"
volumes:
  passvault_pg_data:
networks:
  app-network:
    driver: bridge
